### PR TITLE
Removing int16 association from DaqMxRawData

### PR DESCRIPTION
**Pull request by rfried**
Applying minimal fix for this issue:
https://github.com/adamreeve/npTDMS/issues/112

### CODE REVIEW

**Comment by adamreeve** [comment]
Thanks, looks like there probably needs to be a way to explicitly specify the type if someone did want it to be DaqMxRawData (and that would also help with #114), but this seems sensible for now.

**Comment by rfried** [comment]
How do I get this into a new Pypi build?
https://pypi.org/project/npTDMS/

I would like to be able to pull this down through pip officially for a project I'm working on.

**Comment by adamreeve** [comment]
I've pushed this to PyPi as version 0.14

**Comment by rfried** [comment]
thanks!

**Pull request merged**
