### PR TITLE
Support for tdsTypeDAQmxRawData

### PR DESCRIPTION
**Pull request by nmgeek**
As per #24 I took the patches from PierreSchnizer then fixed the bug that was getting the sample data_size value from the wrong place.

We should also add regression tests to this delta.

### CODE REVIEW

**Comment by nmgeek** [comment]
Ok @adamreeve I believe this pull request is clean ... no duplicate commits.  And I cleaned up the logging as you suggested.

**Comment by adamreeve** [comment]
This looks good thanks! Did you think that the `data` attribute of `TdmsObject` should be the scaled data though? And then there could be a `raw_data` property to get the raw data. I think that would make more sense from a user's point of view, they're more likely to want the scaled data by default and not usually need the raw data. I'd also like some regression tests before merging this.

**Comment by jshridha** [comment]
@adamreeve I gave @nmgeek with a commit that should handle that. I believe he's planning on bringing that commit into this pull request, but hasn't had the chance to do that yet. With the holidays and all, I expect it may be a few days before this is fully finished.

**Comment by nmgeek** [comment]
@adamreeve The scaling via the 'data' attribute and not scaling using the 'raw_data' attribute has been added to this pull request.  I also added a test with a small sample TDMS file.  I added another small TDMS file with the old 'implicitly scaled' data in case someone wants to add more tests that use real TDMS files.

I did not add jshridha's example raw-formatted tdms file since it is large.  That file uses polynomial scaling so we don't have a test which verifies that functionality.

**Comment by adamreeve** [comment]
Thanks @nmgeek, this looks good.

**Comment by adamreeve** [comment]
@nmgeek and @jshridha, I updated the readme to remove the part about DAQmx raw data not being supported and added you both to the contributors section. If you want to have your real names there just let me know or make a pull request to update that.

**Comment by jshridha** [comment]
That sounds good. Feel free to loop me in on any issues that arise. I know
the code pretty well at this point and may be able to help out.

**Comment by nmgeek** [comment]
Thanks @adamreeve.

**Comment by jshridha** [comment]
@adamreeve can you bump the nptdms version and push a build to pypi?

**Comment by adamreeve** [comment]
@jshridha, sure, I just pushed this to PyPI as version 0.9.0.

**Pull request merged**
