### PR TITLE
HDF5 fix

### PR DESCRIPTION
**Pull request by Gygger**
I'm new to Git and Python so this is my first PR.  Hopefully I done good...

These changes fix npTDMS's usage of h5py regarding strings.  h5py issue is [#289](https://github.com/h5py/h5py/issues/289).

The [fix](https://github.com/h5py/h5py/issues/289#issuecomment-329853651) comes thanks to @dpfoose.

I also added an as_hdf check to tdms_test.py .

### CODE REVIEW

**Comment by Gygger** [comment]
Seems like h5py is not listed as an install requirement in setup.py.  I'm going to add it.

`install_requires = ['numpy'],` &rarr; `install_requires = ['numpy', 'h5py'],`

**Comment by adamreeve** [comment]
Thanks for making a PR and including a test! I've added the python-h5py and python3-h5py packages to the Docker image used to run the tests under wercker, so you should be able to remove the extra install requirement and wercker step now. I'd prefer to not have nptdms depend on h5py, it should be an optional dependency and only  needed if people want to be able to export as hdf.

I noticed a warning being printed in the test output which is caused by the data sizes being slightly off, I needed to update your test code to fix the warning:
```
              # Number of bytes in data                                                                                                                                                                              
              "2B 00 00 00"                                                                                                                                                                                          
              "00 00 00 00"                                                                                                                                                                                          
              # Number of properties (0)                                                                                                                                                                             
              "00 00 00 00")                                                                                                                                                                                         
          data = (                                                                                                                                                                                                   
              "06 00 00 00"  # index to after first string                                                                                                                                                           
              "23 00 00 00"  # index to after second string                                                                                                                                                          
          )  
```
The "number of bytes in data" includes the size taken up by the index into the strings.

I'm not very familiar with hdf, but according to the [strings in hdf5 documentation](http://docs.h5py.org/en/latest/strings.html), it looks like the np.string_ type should only be used for scalar attributes, which might be why the test is failing. For unicode data it suggests using something like:
```
unicode_datatype = h5py.special_dtype(vlen=unicode)
dset = f.create_dataset("name", (100,), dtype=unicode_datatype)
```

**Comment by Jonathan-J-Deng** [comment]
Hey Gygger I recently made some small changes to as_hdf function which made some conflicts with your changes.

Can I help with anything to resolve them?

**Comment by Gygger** [comment]
Definitely.  I had some stuff come up that has kept me from doing more on
this.

**Comment by Jonathan-J-Deng** [comment]
def as_hdf(self, filepath, mode='w', group='/'):
        """
        Converts the TDMS file into an HDF5 file

        :param filepath: The path of the HDF5 file you want to write to.
        :param mode: The write mode of the HDF5 file. This can be w, a ...
        :param group: A group in the HDF5 file that will contain the TDMS data.
        """
        import h5py

        # Groups in TDMS are mapped to the first level of the HDF5 hierarchy

        # Channels in TDMS are then mapped to the second level of the HDF5
        # hierarchy, under the appropriate groups.

        # Properties in TDMS are mapped to attributes in HDF5.
        # These all exist under the appropriate, channel group etc.

        h5file = h5py.File(filepath, mode)

        container_group = None
        if group in h5file:
            container_group = h5file[group]
        else:
            container_group = h5file.create_group(group)

        # First write the properties at the root level
        try:
            root = self.object()
            for property_name, property_value in root.properties.items():
                container_group.attrs[property_name] = property_value
        except KeyError:
            # No root object present
            pass

        # Now iterate through groups and channels,
        # writing the properties and data
        for group_name in self.groups():
            try:
                group = self.object(group_name)

                # Write the group's properties
                for prop_name, prop_value in group.properties.items():
                    container_group[group_name].attrs[prop_name] = prop_value

            except KeyError:
                # No group object present
                pass

            # Write properties and data for each channel
            for channel in self.group_channels(group_name):
                for prop_name, prop_value in channel.properties.items():
                    container_group.attrs[prop_name] = prop_value

                # This is a workaround for utf-8 types in h5py
                channel_data = None
                if channel.data_type is types.String:
                    channel_data = np.string_(channel.data)
                else:
                    channel_data = channel.data

                container_group[group_name+'/'+channel.channel] = channel.data

        return h5file

I think this code should resolve conflicts

**Comment by carlodri** [comment]
> I'd prefer to not have nptdms depend on h5py, it should be an optional dependency and only needed if people want to be able to export as hdf.

seems like you should use the `extras_require` section in `setup.py` (docs [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies))

**Comment by adamreeve** [comment]
Apologies for leaving this open for so long. I've now merged this fix in #163 but changed to always using variable length UTF-8 strings rather than fixed length strings in order to support non ASCII data and have consistent behaviour when exporting string data.

The reason the tests were failing for this PR is that calling `numpy._string` on a list of unicode objects in Python 2.7 resulted in a single string representation of the array rather than an array of multiple strings.

I've also recently added `hdf` to `extras_require` in `setup.py` as suggested.

**Pull request closed without merging**
