### PR TITLE
Added option to TdmsObject.as_dataframe to use absolute times

### PR DESCRIPTION
**Pull request by rubdos**
Added option to TdmsObject.as_dataframe to use absolute times instead of relative times generated by time_track.

Our system used pandas' `datetime` objects, so I decided the easiest way to comply with existing stuff would be adding this flag. Calling the function without arguments yields the same as before, calling it with `absoluteTime=True` yields pandas' `datetime` objects with absolute timestamps.

This is an edit upon the method I wrote earlier. If you want me to implement the same functionality for the `TdmsFile.as_dataframe` (which, I think can be simplified more than it is right now too), give me a call.

Tested and working
screenshot from 2015-07-09 13-14-44
screenshot from 2015-07-09 13-14-36

### CODE REVIEW

**Comment by rubdos** [comment]
Please wait with merging this. Someone reported a big performance hit doing it this way. Give me a minute or 10.

**Comment by rubdos** [comment]
As I state in the commit message,
   > Bad performance was noticed with large amounts of data when using
   > the absoluteTime=True attribute. Using the pandas' date_range, which
   > I added in a separate method (pandas_time_track), boosts performance
   > approximately by factor > 10.

this thing is much faster. We're using some millions of measurements.

We're looking forward to the next release ;-)

**Comment by rubdos** [comment]
Sorry for the hassle, apparently pandas can't live with a floating point string as frequency. This fixes it.

**Comment by adamreeve** [comment]
Looks good thanks :+1:

**Comment by rubdos** [comment]
@adamreeve, apparently, there's a problem using the patch I sent in for the performance hit. It rounds the increment, so that the timestamp looses accuracy.

It differs by a lot of time, but pandas doesn't support a frequency as input, only an interval.

I'm going to try to solve this.

**Pull request merged**
